language: java

services:
  - docker

before_install:
- docker pull rabbitmq:3-management
- ./start_test_environment.sh

script:
  - mvn jacoco:prepare-agent test -B jacoco:report

after_success:
  - LATEST_VERSION="$(curl -Ls https://api.bintray.com/packages/codacy/Binaries/codacy-coverage-reporter/versions/_latest | jq -r .name)"
  - curl -Ls -o codacy-coverage-reporter "https://dl.bintray.com/codacy/Binaries/${LATEST_VERSION}/codacy-coverage-reporter-linux"
  - chmod +x codacy-coverage-reporter
  - ./codacy-coverage-reporter report -l Java -r target/site/jacoco-aggregate/jacoco.xml

cache:
  directories:
    - $HOME/.m2
